Fix system tests run script
Forgot to update the system tests run script to explicitly exit status
code.  Needed in order that system tests do not appear to be passing
when they in fact have some or all of the system tests failing.

diff --git a/scripts/run-system-tests b/scripts/run-system-tests
--- a/scripts/run-system-tests
+++ b/scripts/run-system-tests
@@ -68,13 +68,15 @@ do
     numtests=$(( numtests + 1 ))
 done
 
-# report results over all of the tests
+# report results over all of the tests, set explicit code to indicate success/failure
 if [ ${passed} -eq ${numtests} ]
 then
     echo -e "${GREEN}===============================================================================${NORMAL}"
     echo -e "${GREEN}All system tests passed    ${NORMAL} (${passed} tests passed of ${numtests} system tests)"
+    exit 0
 else
     echo -e "${RED}===============================================================================${NORMAL}"
     echo -e "${RED}System test failures detected${NORMAL} (${passed} tests passed of ${numtests} system tests)"
+    exit 1
 fi
 
